// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpaaruwchhouojnoegfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwYWFydXdjaGhvdW9qbm9lZ2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3MjUwNDMsImV4cCI6MjA4ODMwMTA0M30.ubxArRkc_xEHSR5C6dqePoiNsSPs-sAxFJr_xZgCZhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});